# Generated by Django 4.0.3 on 2022-06-19 23:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilSocial',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateField(blank=True, null=True, verbose_name='Fecha Creación')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=35, null=True, verbose_name='Nombre')),
                ('ap1', models.CharField(blank=True, max_length=35, null=True, verbose_name='Apellido 1')),
                ('ap2', models.CharField(blank=True, max_length=35, null=True, verbose_name='Apellido 2')),
                ('email', models.CharField(max_length=25, verbose_name='Email')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('factura', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Factura')),
                ('perfilsocial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.perfilsocial')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Registrado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('telefono', models.CharField(blank=True, max_length=9, null=True, verbose_name='Telefono')),
                ('fecha_registro', models.DateField(blank=True, null=True, verbose_name='Fecha Registro')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='perfilsocial',
            name='nombre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.registrado'),
        ),
        migrations.CreateModel(
            name='Compras',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Precio')),
                ('perfilsocial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.perfilsocial')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.registrado')),
            ],
        ),
    ]
