# Generated by Django 4.0.3 on 2022-06-23 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_ventas_perfilsocial_remove_ventas_usuario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='ap1',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='ap2',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='email',
        ),
    ]
