# Generated by Django 4.0.3 on 2022-05-14 16:27

from django.db import migrations, models
import photos.validators


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_photo_owner_photo_visibility_alter_photo_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='description',
            field=models.TextField(blank=True, null=True, validators=[photos.validators.badwords]),
        ),
    ]
