# Generated by Django 4.0.3 on 2022-06-19 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_alter_photo_description'),
        ('photos', '0009_alter_photo_image'),
    ]

    operations = [
    ]
