# Generated by Django 4.0.3 on 2022-06-19 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0010_merge_20220619_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='albums/images/'),
        ),
    ]
