# Generated by Django 4.0.3 on 2022-06-24 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0014_remove_photo_image_photo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='license',
            field=models.CharField(choices=[('Copyright', 'Copyright'), ('Copyleft', 'Copyleft'), ('Creative commons', 'Creative commons')], default='Creative commons', max_length=16),
        ),
        migrations.AlterField(
            model_name='photo',
            name='visibility',
            field=models.CharField(choices=[('Pública', 'Pública'), ('Privada', 'Privada')], default='Pública', max_length=7),
        ),
    ]
